feat: test commitment mining logic when forked
workhard-finance/protocol pull request #2
Opened 2021-06-19 15:09 UTC by zzorum

2021-06-19 20:55 UTC, 0xMayflower requested changes

2021-06-19 20:55 UTC, 0xMayflower commented on test/integration.test.ts
> +      expect(afterAliceVisionVal.sub(beforeAliceVisionVal).isNegative()).is.eq(
I recommend you to use `expect(a).to.be.gt(b)`

2021-06-19 20:55 UTC, 0xMayflower commented on test/integration.test.ts
> +      await goTo(day * 3);
This line should be in the runOnly

2021-06-19 20:55 UTC, 0xMayflower commented on test/integration.test.ts
> +        console.log(
Let's remove this logging ;)

2021-06-20 09:16 UTC, zzorum commented
@0xMayflower applied + additional testcase added. still in progress

2021-06-21 00:40 UTC, 0xMayflower commented on test/integration.test.ts
> +      it("successfully add new funds", async () => {
Recommend you to use this pattern :)
```
describe("add new funds", ()=> {
  runOnly(async() => {
    // transactions
  })
  it("statements", async () => {
    // expect statements.
  })
})
```

2021-06-21 13:09 UTC, merged

2021-06-21 13:09 UTC, 0xMayflower commented
Merged them for the deployment preparation :) Please keep writing up the remaining cases!